### ISSUE TITLE
How to make active on tab by default and click button to deactivate?

### ISSUE THREAD

**Issue by pooriaarab** [ansh/bionic-reading#10]
Hi, 

Gr8 job acting on this quick btw. 

I'd like this to be active by default and use the convert button from the extension to turn it off. 

How can I do that?

**Comment by asieduernest12** [comment]
I will probably work on this , but a solution is to add a css flag on the body element, so when bionic mode is on you can have .bionic-on and then remove it when bionic mod e is off

**Comment by X140Yu** [comment]
Hi @pooriaarab @asieduernest12 
I've added a checkbox to toggle reading on default, also added support for reverting page back to normal when click the toggle button again, can pull from the latest master and give it a try

<img width="237" alt="image" src="https://user-images.githubusercontent.com/7059872/169701644-f0c27cf4-8b8c-4610-ae30-cda8524fb99e.png">
