### ISSUE TITLE
It's been working but it is ify

### ISSUE THREAD

**Issue by Blac-Supernova** [ansh/bionic-reading#12]
It doesn't work on sites like youtube but when it does work its pretty good. when it converts the text, it gets rid of all other formatting that the text might have had like hyperlinks. Videos on the page tend to disappear too. But considering that I've only heard about bionic reading a couple of days ago and you you already made a pretty functional extension so fast, I think that's pretty cool.

**Comment by ansh** [comment]
@Blac-Supernova This issue has been fixed with the help of @X140Yu
