### ISSUE TITLE
Curious to hear about patent get around

### ISSUE THREAD

**Issue by benjaminbialy** [ansh/bionic-reading#16]
Hey Mate,

Just wondering if you're aware that the original guy has a patent on this tech, wouldn't want you to get sued.

**Comment by Alexnortung** [comment]
I am curious on what they actually have a patent on? Because you cannot patent an algorithm and bionic reading is basically an algorithm.
I understand that they can have a trademark, which should probably also be respected if/when this project is released.

**Comment by Doohwancho** [comment]
this is a link to patent
https://bionic-reading.com/patent-trademark-2/

@Alexnortung you can patent on algorithm. for example, in South Korea, a game company patented on algorithm: if a player is doing gatcha, the more players around him, the higher chance of getting legendary item.(so that he can boast it and motivate other players to gatcha)

**Comment by IBRice101** [comment]
The actual UK version of the patent (as opposed to a link to their site) can be found [here](https://patentimages.storage.googleapis.com/96/4d/2b/749f7a4c791eea/GB2552586A.pdf), it describes something that is, in my opinion (not a Lawyer) something that is way too generic to be patented, simply bolding the first 3/5th of the word

![An image showing Figure 2.B and Figure 3 of the patent, describing the "algorithm" that is used](https://user-images.githubusercontent.com/26672949/169700269-b4a4ebac-b892-46af-8ed1-a3dad9c6bc1f.png)

**Comment by X140Yu** [comment]
#23

**Comment by benjaminbialy** [comment]
> I am curious on what they actually have a patent on? Because you cannot patent an algorithm and bionic reading is basically an algorithm. I understand that they can have a trademark, which should probably also be respected if/when this project is released.

Yeah, it blows my mind how they managed to get one but they did in France. They've also got one pending in Germany. Now that I think of it, this repo is definitely breaching their trademark lol. You can check out their website https://bionic-reading.com/patent-trademark-2/ 

But on the point of the algorithms not being patentable, wtf lol. I agree. I'm no lawyer but I thought software could be patented but not the underlying algorithms. Who knows.

Another place where being a lawyer would help is can I use it outside of France? You'd think so as patents are supposed to only be territorial. Who knows though

**Comment by davmlaw** [comment]
> simply bolding the first 3/5th of the word

Can you bold the first 1/2 or 7/10ths of the word?

You could also try rounding up 1/2 and down 7/10ths?

**Comment by lquenti** [comment]
the bigger problem probably will be the naming of the repo...

**Comment by ansh** [comment]
If the name of the repo is an issue, we are happy to change it. 

There has been no issue as of yet.

**Comment by Exclusif66** [comment]
The french patent doesn't even require their algorithm to be followed, just "at least one of the rules" of the algorithm. Absolute madness.
