### ISSUE TITLE
Straight up just doesn't work 👍

### ISSUE THREAD

**Issue by tylerabernathy** [ansh/bionic-reading#2]

**Comment by davidwisseh** [comment]
1. Download code as zip.
![download](https://user-images.githubusercontent.com/15909768/169638232-7f664570-1cc8-4c9b-8954-5e4ad9d6ec72.png)

2. extract.
![extract](https://user-images.githubusercontent.com/15909768/169638240-df7e0fd8-bbc9-4f9b-9df0-bde4908540af.png)

3. Open extensions in chrome settings.
![extensions](https://user-images.githubusercontent.com/15909768/169638245-852414ad-ddb4-4308-90c9-08077b433e5b.png)

4. Enable developer mode.
![developer](https://user-images.githubusercontent.com/15909768/169638247-6d2fefee-7fe7-4bbf-aec2-0ab2a8401bdb.png)

5. "Load unpacked" select the folder you extracted to.
![load unpacked](https://user-images.githubusercontent.com/15909768/169638261-563a64cc-019d-4d1e-929d-030c2c577d8f.png)
![select folder](https://user-images.githubusercontent.com/15909768/169638257-54d9a69b-d577-4353-ac5a-6b99a910ff07.png)

6. Click on extension.  should be under "access requested".
![access](https://user-images.githubusercontent.com/15909768/169638268-47f74e01-455c-4222-8b82-4d79bb4e1ea0.png)

7. Click convert.
![convert](https://user-images.githubusercontent.com/15909768/169638273-b70c3aaf-8a52-4dd0-bf58-a4a7dffe8608.png)

**Comment by ansh** [comment]
@tylerabernathy Can you please elaborate on the issue?

**Comment by davidwisseh** [comment]
> @tylerabernathy Can you please elaborate on the issue?

you didn't show people how to use the extension. I had to google how to set it up.

**Comment by ansh** [comment]
@davidwisseh Thank you for making the instructions!

 This was a side project I cranked out in less than 15 minutes, not a production-ready Chrome Extension. Hope that makes sense!

Can you put your instructions the a README and open a PR? Happy to merge.

**Comment by asieduernest12** [comment]
> > @tylerabernathy Can you please elaborate on the issue?
> 
> you didn't show people how to use the extension. I had to google how to set it up.

be nice, the project just started

**Comment by dmrobotix** [comment]
It works fine for me, figured this was very new, so I installed it as a developer user of Chrome. Just wanted to say thanks for your effort.

**Comment by fennelcakes** [comment]
Thanks for making this! This is awesome. 
Just wanted to add, on some sites it doesn't want to work in every frame but it's easy to get around by switching the site to Reader Mode (with an extension like Reader Mode)
