### ISSUE TITLE
Convert button errors

### ISSUE THREAD

**Issue by sarahswhite1987** [ansh/bionic-reading#21]
Hi!

I try to install this as an extension, but when I hit "convert", it errors:

src/popup.html:0 (anonymous function)

What am I doing wrong?

Cheers!

**Comment by ansh** [comment]
@sarahswhite1987 Can you put a screenshot of your error here? 

Also, please try downloading it again. The community has made a lot of updates.

**Comment by asieduernest12** [comment]
@sarahswhite1987 as @ansh definitely check the latest build release. It should work for you now. 

Please close this ticket too
