### ISSUE TITLE
Convert button - multiple clicking breaks the text

### ISSUE THREAD

**Issue by Alz2709** [ansh/bionic-reading#22]
Thank you for the tool, it is really helpful. 

When clicking the button once, everything works great. I wanted to revert the text to "normal" by clicking the Convert button again, but this somehow breaks the text and can only be fixed by re-loading the page. 

Desired outcome: when clicking the Convert button again, the text would go to "normal". 

Current workaround: refresh page. 

Thank you.

**Comment by X140Yu** [comment]
Hi @Alz2709, thanks for the feedback, have fixed it on the lasted master, can pull the code and give it a try

**Comment by Alz2709** [comment]
Thank you, the fix works perfectly
