### ISSUE TITLE
Explain what bionic reading is in the readme

### ISSUE THREAD

**Issue by ianchanning** [ansh/bionic-reading#35]
I had no idea what bionic reading was when coming here. So it would be useful if you would link to https://bionic-reading.com/ or give a quick explanation in the README

**Comment by ansh** [comment]
@ianchanning It has been added to the README

Out of curiosity, if you didn’t know what Bionic Reading was, how did you find this repository?

**Comment by rozari0** [comment]
> @ianchanning It has been added to the README
> 
> Out of curiosity, if you didn’t know what Bionic Reading was, how did you find this repository?

There is a telegram channel named 'Github Repos' with huge subscriber promoted this repo. :3

**Comment by ianchanning** [comment]
Great thanks! It's on front page of [Hacker News](https://news.ycombinator.com/) :wink: 

![Screenshot from 2022-05-23 13-54-19](https://user-images.githubusercontent.com/233318/169813813-a13121ec-3604-4c31-8351-1f5c48b7bfe7.png)
