### ISSUE TITLE
Gmail hit or miss

### ISSUE THREAD

**Issue by shanold** [ansh/bionic-reading#36]
It really seems to depend on the font used, Some bits of text in Gmail it works on and other bits It doesn't Even within the message.

**Comment by gregoryxandrew** [comment]
I'm also having this. Some top-level emails load but then all emails below don't? Sort of strange, not sure what's causing it.

**Comment by asieduernest12** [comment]
They are dynamic added after the BR parser has executed

**Comment by asieduernest12** [comment]
it is hard to account for dynamic elements injected into the page when you set the extension to load on page open
so functionality has to enable rebolding on new elements
