### ISSUE TITLE
left and right buttons break after clicking on this page with extension toggled

### ISSUE THREAD

**Issue by kicksent** [ansh/bionic-reading#43]
https://www.solidjs.com/tutorial/bindings_events

Reproduce by clicking on the left and right arrows. Notice that the buttons stop working if the tool is toggled. Turning off the toggle for this reader fixes the issue. 

![image](https://user-images.githubusercontent.com/9921926/169891289-ea529b98-c49d-4b75-b92f-b459036b0090.png)

**Comment by bolshoytoster** [comment]
@kicksent I'm not able to reproduce this, but I am getting the extension not affecting the text when you click the arrows, if that's what you meant.
