### ISSUE TITLE
The button will not work in the reading mode

### ISSUE THREAD

**Issue by hstk30** [ansh/bionic-reading#45]
<img width="93" alt="image" src="https://user-images.githubusercontent.com/42362747/169935679-77e0ddb3-dd5d-48d4-90b0-7fc29e685d39.png">

Like that button .

**Comment by hstk30** [comment]
Acctually, is the gitlab' button. Like a random project [batman](https://gitlab.com/cerfacs/batman), 

<img width="607" alt="image" src="https://user-images.githubusercontent.com/42362747/170174044-98dc0086-3748-4eac-9277-40a548da27aa.png">

The button not work.

**Comment by ansh** [comment]
Fixed in #85
