### ISSUE TITLE
any way to adapt this to languages like Chinese

### ISSUE THREAD

**Issue by simin75simin** [ansh/bionic-reading#46]
Chinese is not made of letters and individual 'letters' have a rather diverse, independent meaning. Is there any way to adapt this?

ReadHub manages to extract STEM articles in Chiense rather well but opening this extension on a normal csdn article does not look good.

(author also posted on v2ex a while back..)

**Comment by X140Yu** [comment]
@simin75simin 

目前的插件没有对于中文进行优化，如果要适配中文那就需要对中文句子进行分词切割，然后高亮开头的几个字。不太确定这种阅读方式是否适合中文，可以先做个实验看看

**Comment by hxhc** [comment]
中文阅读也需要这种吗？感觉和中文自带Bionic reading效果啊

**Comment by X140Yu** [comment]
@hxhc 确实，中文已经足够简略了，再略过某些字的话很容易产生歧义

**Comment by Cveinnt** [comment]
Bionic reading is optimized for alphabetical languages, whereas Chinese is a symbolic language - I don't think it's quite possible to use bionic reading for Chinese, unless you are highlighting strokes in Chinese characters...

**Comment by ansh** [comment]
@X140Yu I will leave this issue unto your discretion.

**Comment by X140Yu** [comment]
Closed as won't do
