### ISSUE TITLE
No 'Access Requested' and Errors

### ISSUE THREAD

**Issue by Swooz777** [ansh/bionic-reading#49]
During installation process it appeared straight under 'Full Access' in my extensions list.

Doesn't work, here's the errors:
Uncaught (in promise) Error: Cannot access a chrome:// URL
Context
src/popup.html
Stack Trace
src/popup.html:0 (anonymous function)

Uncaught (in promise) Error: Cannot access a chrome:// URL
Context
src/background.js
Stack Trace
src/background.js:0 (anonymous function)

**Comment by Swooz777** [comment]
Ok now it seems to work even with errors.

**Comment by Swooz777** [comment]
Ok now it seems to work even with errors.

**Comment by ansh** [comment]
@Swooz777 You cannot use this extension on sites that begin with chrome://

That is a limitation to most extensions.
