### ISSUE TITLE
Can you make it for Firefox? 

### ISSUE THREAD

**Issue by HugoRbh** [ansh/bionic-reading#5]
Hello, can you do the same for firefox? Thank you

**Comment by amatzen** [comment]
I will suggest the maintainers use https://www.npmjs.com/package/webextension-polyfill to ensure cross browser support.

**Comment by ansh** [comment]
Firefox support coming in the next 12 hours.

**Comment by HugoRbh** [comment]
Nice !

**Comment by not-matthias** [comment]
Can't wait to try it out!

**Comment by j3ffh95** [comment]
Awesome!

**Comment by Gregory108** [comment]
Will it be Firefox support or a published extension?

**Comment by paskozdilar** [comment]
Looking forward to the Firefox version. Kudos!

**Comment by crox-safe** [comment]
> Firefox support coming in the next 12 hours.

Any eta for firefox support?

**Comment by jeremiah-miller** [comment]
I see that the commits show firefox is supported, how do you install it on firefox though?

**Comment by X140Yu** [comment]
Check out the latest doc here https://github.com/ansh/bionic-reading#firefox
