### ISSUE TITLE
Potential patent issue on project name

### ISSUE THREAD

**Issue by ChoKaPeek** [ansh/bionic-reading#52]
Hi there, I am assuming you know about the origin / hype / patent associated with Bionic Reading GmbH's solutions.

I strongly agree that this should stay open-source, this is a simple piece of code, plus I am not a lawyer, but you might head into trouble with the _naming_ of your project.

Just in case, here is a link to the patent / trademarks on their names: https://bionic-reading.com/patent-trademark-2/

Feel free to close.

**Comment by nathan-beam** [comment]
+1 on this. This project looks awesome, I would hate to see it taken down for patents

**Comment by ansh** [comment]
Thank you for raising this issue. If there is a problem, we will change the name to Jiffy Reader. At the moment, there has not been any issues.
