### ISSUE TITLE
Don't process text in code block.

### ISSUE THREAD

**Issue by shaneing** [ansh/bionic-reading#57]
For example:

- https://docs.tendermint.com/master/tendermint-core/consensus/reactor.html#reactor

**Comment by winkbrace** [comment]
Hm, they use a `<span class="codeblock">`. That's hard to detect. Normally code blocks are rendered in `<pre>` tags which are excluded.

**Comment by shaneing** [comment]
I don't know if the extension excludes the tag by the custom rule. eg, `class="codeblock"`.

> Hm, they use a `<span class="codeblock">`. That's hard to detect. Normally code blocks are rendered in `\<pre\>` tags which are excluded.
