### ISSUE TITLE
Using Manifest v2 in Output Extension

### ISSUE THREAD

**Issue by wjwalcher** [ansh/bionic-reading#63]
Since (it appears) this project has moved to using node, the extensions output by the build use manifest v2, which is deprecated and will lose support in 2023. 
This should be changed back to manifest v3.

**Comment by Cveinnt** [comment]
It looks like migrating to V3 manifest is a bit more complicated then I thought - the webpack-extension-reloader package used for this extension is no longer maintained and does not support V3 (more [here](https://github.com/rubenspgcavalcante/webpack-extension-reloader/issues/125)) which means the service worker registration will fail for v3 manifests.

**Comment by ansh** [comment]
Closed in favor of #68
