### ISSUE TITLE
Adding HTML to Bionic Reading

### ISSUE THREAD

**Issue by batuhankrbb** [ansh/bionic-reading#64]
Can you please add the option to convert html to bionic reading instead of just converting plain text?

**Comment by asieduernest12** [comment]
can you explain further and give an example so that someone or even you could then implement it and then submit as a pr

**Comment by batuhankrbb** [comment]
Sure, I'm using this code (only convert.js) as an API for my mobile application. In the official bionic reading API, you send an HTML string and get the bionic version of that HTML string. But in this code, you can't send HTML strings to have them converted.

**Comment by ansh** [comment]
This is out of the the scope of this project. We are making a Browser Extension not a general purpose API.
