### ISSUE TITLE
Firefox extension is corrupt

### ISSUE THREAD

**Issue by carterchannui** [ansh/bionic-reading#66]
I followed the installation instructions and it appears that the generated `firefox.xpi` file is corrupt.

![Screen Shot 2022-05-25 at 10 08 40 AM](https://user-images.githubusercontent.com/26908609/170321097-508a0d7a-b051-42d9-8f4d-95711d881cd2.png)

**Comment by radiden** [comment]
Same thing happens here, Firefox version:
![image](https://user-images.githubusercontent.com/28237353/170329489-ee36c2c5-a22e-487b-9451-c33bc7a4a1b6.png)

**Comment by YetAnotherDevWannabe** [comment]
where did you even found that ? :D

**Comment by X140Yu** [comment]
Hi @carterchannui @radiden @YetAnotherDevWannabe 

- Unzip the downloaded `firefox.xpi` file here https://github.com/ansh/bionic-reading/releases/tag/0.0.1
- In Firefox: Extension - Debug Add-on - Load Tmp Add-on, select the manifest.json in the unzipped folder

I'll add the instructions later in README

**Comment by carterchannui** [comment]
That worked, thank you.

**Comment by Gregory108** [comment]
Worked for me only if downloaded from another browser, otherwise I cannot make FF download `.xpi`.

Also, does the following deserves to be a feature suggestion? To make links in instructions do all the job for the user (clickable link to download `.xpi`, clickable link to `about:`)

**Comment by Gregory108** [comment]
@X140Yu Wrt link to download file, how about this [approach](https://stackoverflow.com/questions/24987542/is-there-a-link-to-github-for-downloading-a-file-in-the-latest-release-of-a-repo/54836319#54836319)? Is it possible to make some use of it?

`about:debugging#/runtime/this-firefox` it seems is indeed impossible to link to (for "security reasons"?)

But, anyway, best automation would be not to make this manual simple, but to make the plugin official=)

**Comment by anjannair** [comment]
> Worked for me only if downloaded from another browser, otherwise I cannot make FF download `.xpi`.

For users with Linux and WIndows just run `wget https://github.com/ansh/bionic-reading/releases/download/0.0.1/firefox.xpi` in your terminal in your preferred directory and load it from there!
