### ISSUE TITLE
Failed to Load: Manifest File Missing or Unreadable

### ISSUE THREAD

**Issue by dejer** [ansh/bionic-reading#67]
![image](https://user-images.githubusercontent.com/61756639/170323123-766aec02-c7c3-4b97-a247-c6ceae15994c.png)

See attached image. Text also copied below:

Failed to load extension
File:     D:\My Documents\Downloads\Software\Bionic Reading\bionic-reading-master\bionic-reading-master
Error
Manifest file is missing or unreadable
Could not load manifest.

Browser details: [Version 1.38.119 Chromium: 101.0.4951.67 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by TheCedarPrince** [comment]
I have this same error on OSX.

**Comment by zombiehoffa** [comment]
Same problem here on linux and brave.

**Comment by FahimFBA** [comment]
Follow the PR #65 
That should solve the error.

**Comment by TheCedarPrince** [comment]
Brilliant - that worked, thanks @FahimFBA 😄

**Comment by TLausZ** [comment]
After the build I had to select the proper directory in the sub directory extension:
![image](https://user-images.githubusercontent.com/9079817/170360997-73805090-4073-4c45-8d7e-19aaa2a5541f.png)

**Comment by yom96** [comment]
Struggling to install on Chromebook - any ideas?

**Comment by X140Yu** [comment]
You can download the latest release here https://github.com/ansh/bionic-reading/releases/tag/0.0.1 no need to build yourself
