### ISSUE TITLE
Reading Mode Cannot be Toggled Off

### ISSUE THREAD

**Issue by Cveinnt** [ansh/bionic-reading#73]
Not sure if this is a system specific problem, but for me, the extension can only be toggled on, then it's impossible to turn it off, regardless of how many times I pressed the "toggle" button. The only workaround I found is to refresh the page.

System specs: macOS Monterey, on Chrome Version 101.0.4951.64 (Official Build) (x86_64), using the latest build on GitHub.

**Comment by X140Yu** [comment]
It seems this problem happens occasionally
