### ISSUE TITLE
Is "Jiffy Reader" this repository?

### ISSUE THREAD

**Issue by shenef** [ansh/bionic-reading#74]
https://www.jiffyreader.com/ (which is linked on this repo) seems to be affiliated to this repo.
To be honest, it seems a little dodgy to me that this isn't mentioned anywhere, I couldn't find anything about "Jiffy Reader Inc" and that the page does not have a privacy policy while also collecting email addresses.

**Comment by ansh** [comment]
@shenef Thank you for this issue.

As you can see this project started less than 5 days ago. JiffyReader was a simple page we built to be able to collect emails and inform users when the Chrome Extension was on the web store. 

The privacy policy will be added to https://www.jiffyreader.com/privacy soon
