### ISSUE TITLE
0.0.2 firefox extension not installing

### ISSUE THREAD

**Issue by MattDarkPro** [ansh/bionic-reading#81]
#### Runtime Environment

- Operating system and version: [Windows 10 Build 19043.1110]
- Browser and version: [Firefox 100.0.2 (64-bit)]
- `bionic-reader` version or commit: [`0.0.2`]

#### Current Behavior
If I go to https://github.com/ansh/bionic-reading/releases/download/0.0.2/firefox.xpi it doesn't install it, stating that "The add-on downloaded from this site could not be installed because it appears to be corrupt.
#### Expected Behavior
That the firefox.xpi file downloads

#### Steps to Reproduce

1. Go to https://github.com/ansh/bionic-reading/releases/download/0.0.2/firefox.xpi on the Firefox browser.

#### Images / Videos 
![image](https://user-images.githubusercontent.com/40952643/170685686-2f283951-7f6f-41a4-a3fe-eb8dbef6924a.png)

**Comment by X140Yu** [comment]
@MattDarkPro try to download it with a different browser, it seems Firefox won't allow downloading unsigned xpi files

**Comment by MattDarkPro** [comment]
@X140Yu Ah, I'm an idiot, it's in the instructions as well, thanks.

**Comment by X140Yu** [comment]
@MattDarkPro No, you're not, update that after your mention 😆
