### ISSUE TITLE
Opera Extension Fails to Install

### ISSUE THREAD

**Issue by Dev-Magus** [ansh/bionic-reading#84]
#### Runtime Environment

- Operating system and version: Windows 10 Build 19043.1706
- Browser and version: Opera Version 86.0.4363.50
- `bionic-reader` version or commit: 0.0.2

#### Current Behavior
Extension fails to install to browser
#### Expected Behavior
Extension installs to browser
#### Context

With no instructions in the README on the main page, I searched Google for how to manually install extensions on Opera as I am new to the browser. Results instructed me to  navigate to "Extensions>Manage Extensions" and then drag and drop the crx file into the field of installed extensions. Upon doing so, I received an error message at the top of my browser, and the extension did not install. Suspecting that perhaps I needed the source data for it to work, I downloaded the zip file and unpacked it in the same directory as the crx file, but received the same results whether the file was inside or outside the folder of the source code. I realize now that there was likely no point in pulling the source code for the purpose of installing the extension, but again I am new to this browser.
#### Steps to Reproduce

1. Download opera.crx file
2. Open Opera browser & navigate to "Extensions>Manage Extensions"
3. Drag opera.crx file from open file explorer window to Opera browser window

#### Traceback

```
Extension Installation failed. Package is invalid: 'CRX_HEADER_INVALID'.
```

#### Images / Videos 

![Opera Extension Fail](https://user-images.githubusercontent.com/106396649/170739433-a019cc9c-7bbe-40d4-b156-e98dc38e21e6.PNG)

**Comment by X140Yu** [comment]
@Dev-Magus 

- Download `chrome.zip` in releases and upzip it
- Enable Developer Mode in Opera Extensions
- Load unzipped folder as unpacked extension

**Comment by ansh** [comment]
@Dev-Magus Does this work now?

**Comment by Dev-Magus** [comment]
@ansh apologies; I've been busy the last few days and only _just_ got an email about a response. Applying that method works! That said, the extension doesn't default on when it's installed, so may need to look into that.
