### ISSUE TITLE
incorrect version number number indicated in browser after release installation

### ISSUE THREAD

**Issue by asieduernest12** [ansh/bionic-reading#93]
#### Current Behavior 
The version indicated after installing any release is showing 1.0.0 in chrome, firefox and opera
![Screenshot from 2022-05-29 13-07-08](https://user-images.githubusercontent.com/20851930/170882677-f7b98b1d-2eb8-44bf-9ce8-eb4b6cc13c8c.png)

#### Expected Behavior
Show a version number corresponding with the release version label/number
The screenshot above in this case is for release 0.0.3

#### Context
User may be reporting issues with incorrect version numbers so far. example

#### Possible Solutions

The build should rewrite the version in the manifest.json that is zipped to be the same as the release version number

To keep this consistent future release on chrome extension store release versions should would now have to start from 1.0.x
so that uploading new updates to chrome extension store is simplified as chrome store guidelines require subsequent versions
to have a higher version number

**Comment by X140Yu** [comment]
the version is related to `version` in `package.json`, added the release guide in [README](https://github.com/ansh/bionic-reading#release-a-new-version)

**Comment by asieduernest12** [comment]
awesome @X140Yu thank you. This [README](https://github.com/ansh/bionic-reading#release-a-new-version) is helpful
