### ISSUE TITLE
error Couldn't find a package.json file

### ISSUE THREAD

**Issue by KenWuqianghao** [ansh/bionic-reading#97]
#### Runtime Environment

- Operating system and version: macOS Monterey
- Browser and version: Brave Version 1.38.119 Chromium: 101.0.4951.67 (Official Build) (arm64)
- `bionic-reader` version or commit: latest

#### Current Behavior
when running yarn build it returns
error Couldn't find a package.json file

#### Context

Possible confusion
#### Possible Solutions
just ignore it and continue, works fine

#### Steps to Reproduce

1.
2.
3.

#### Traceback

```

```

**Comment by X140Yu** [comment]
Hi @KenWuqianghao , doc updated https://github.com/ansh/bionic-reading#chrome-edge-and-chromium-based-browsers no need to install
